name: Build and Deploy to AWS ECS

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    name: Build and Deploy to AWS ECS
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      # Step 3: Build and Push Docker image to Amazon ECR
      - name: Build and Push Docker Image
        env:
          ECR_REPO: ${{ secrets.ECR_REPO_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "Building the Docker image..."
          docker build -t $ECR_REPO .

          echo "Tagging the Docker image..."
          docker tag $ECR_REPO:latest ${{ steps.ecr-login.outputs.registry }}/$ECR_REPO:latest

          echo "Pushing the Docker image to Amazon ECR..."
          docker push ${{ steps.ecr-login.outputs.registry }}/$ECR_REPO:latest

      # Step 4: Deploy the updated image to ECS
      - name: Deploy to ECS
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
          ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
          ECR_IMAGE: ${{ steps.ecr-login.outputs.registry }}/${{ secrets.ECR_REPO_NAME }}:latest
        run: |
          echo "Deploying the updated image to ECS..."
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment
